export const URL_HOME = '/'
export const URL_LOGIN = '/login'
export const URL_ADMIN_HOME = '/admin'
export const URL_REGISTER = '/register'
export const URL_ADRESSE = '/adresse '
export const URL_PANIER ='/panier'